### ISSUE TITLE
Use a proper init script from phusion

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-docker-stack#12] opened 2018-11-13 10:18 UTC
See why here: https://github.com/phusion/baseimage-docker#contents

For services already provided by phusion, check e.g. https://github.com/aiidateam/torquessh_base-docker/blob/17731c2452187adb03661683ba9e25b11b079946/Dockerfile#L36 (note that what one needs to do differs depending on the base image from Phusion).

This to provide more init scripts:
https://github.com/aiidateam/torquessh_base-docker/blob/17731c2452187adb03661683ba9e25b11b079946/Dockerfile#L50

and CMD should always remain `CMD ["/sbin/my_init"]`

**Comment by yakutovicha** [comment] 2019-06-26 14:33
This is to summarize what I learned while trying to figure out how to use the standard `my_init` system provided by phusion.

1. According to the phusion baseimage README there are two ways to execute scripts at container startup: [running them as daemons](https://github.com/phusion/baseimage-docker#adding-additional-daemons) or [place them from `my_init` folder](https://github.com/phusion/baseimage-docker#running-scripts-during-container-startup)

2. What I observed: they both get launched by `/sbin/my_init` program. The scripts from `my_init` get executed first, the daemons get executed second.

3. **PROBLEM1**: This implies that one cannot start postgres as a daemon, because postgres should be started before AiiDA.

4. According to the phusion README the "proper" way to launch scripts and daemons at startup is to add `CMD ["/sbin/my_init"]` to the docker file. Note: there can be only one `CMD` in the docker file.

5. **PROBLEM2**: if I start [`matcloud-jupyterhub-singleuser`](https://github.com/aiidalab/aiidalab-docker-stack/blob/master/matcloud-jupyterhub-singleuser) as a daemon, jupyterhub does not notice it. The only way that worked for me was to run it from `my_init` folder in a blocking manner. Which means the daemons won't start

6. **PROBLEM3**: If I run `matcloud-jupyterhub-singleuser` in a non-blocking manner, the jupyterhub web interface is not able to recognize that the docker container is ready.

7. When launching the docker container [DockerSpawner](https://github.com/jupyterhub/dockerspawner) automatically adds two command line parameters: `'--ip="0.0.0.0"', '--port=8888'`.  According to [these lines](https://github.com/jupyterhub/jupyterhub/blob/f7f82b8214846456f2e1a426ea92667c9db8fe44/jupyterhub/spawner.py#L918-L927) the _proper_ way to delete them would be to add to the following lines to the `jupyterhub_config.py` file:
```
c.DockerSpawner.ip = '' # should be a string
c.DockerSpawner.port = 0 # should be an integer
```

8. **PROBLEM4**: Adding the line `c.DockerSpawner.port = 0` to the jupyterhub_config.py file causes jupyterhub fail to start:
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external
connectivity on endpoint jupyter-aliaksandr_2Eyakutovich_40epfl_2Ech
(2568d4735ef1cd76e0200fdda04f7ce566e17a6c19537628fe8e4d2cb8e84b78):  (iptables failed:
iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32975 -j DNAT --to-destination
172.17.0.2:0 ! -i docker0: iptables v1.6.0: Port `0' not valid
```

So as I conclusion I see two possible solutions:

1. If we want to keep using phusion, we should:
   1.1. Place all the processes in my_init folder (not use them as daemons, **PROBLEM1-3**) and Fix the **PROBLEM4**
or
   1.2 Create our own `CMD` start script.

2. Use another base image. @ltalirz proposed to consider the ones provided by jupyterhub people:
```
jupyter notebook docker containers:
data science nb uses
scipy notebook uses
minimal notebook uses
base notebook uses
ubuntu 16.04
```
@ltalirz, @giovannipizzi  what do you think?

**Comment by yakutovicha** [comment] 2019-06-26 14:56
In the meanwhile I made a temporary fix of the docker spawner (**PROBLEM4**) in dev-aiidalab server to let the aiidalab users to transfer their notebooks to aiida 1.0.

The rabbitmq, postgres,  start-singleuser.sh, matcloud-jupyterhub-singleuser are launched from `/etc/my_init` folder

**Comment by yakutovicha** [comment] 2019-06-27 11:26
I've created  an issue https://github.com/jupyterhub/dockerspawner/issues/319 to discuss the possible solution(s) to the **PROBLEM2**

**Comment by yakutovicha** [comment] 2019-09-21 19:16
some other things I learned when trying to deploy the container under Kubernetes. Just to keep in mind.

1. The reason why physion image exists is that there is no lightweight init system that properly manages zombie tasks. The motivation is described [here](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) in more details. Recommended to read - quite an educational article.
1. According to the article above docker could have taken care of that, but probably they have higher priorities, so this hasn't yet happened.
1. The `/sbin/my_init` script (the lightweight init system) must be run as root. See [this](https://github.com/phusion/baseimage-docker/issues/264#issuecomment-162853995) comment and [this](https://github.com/phusion/baseimage-docker/issues/264#issuecomment-302026661) comment that explains in more details why running as root is unavoidable.
1. For some systems, though, this causes a big problem, like reported [here](https://github.com/phusion/baseimage-docker/issues/264). Using Heroku with Docker containers makes it impossible to use proper physion init system.

**Comment by yakutovicha** [comment] 2019-12-03 17:26
So we can close the story, finally.

1) I couldn't use `/sbin/my_init` script as it is, because JupyterHub docker spawner (as well as the Kubernetes docker spawner) gives some default parameters that I couldn't switch off, see https://github.com/jupyterhub/dockerspawner/issues/319. So the way I overcome the problem is by creating `my_my_init that` has only calls `/sbin/my_init` and doesn't care about command line parameters.

2) The kubespawner issue (N5 in the previous comment) could be resolved by adding 
```
c.KubeSpawner.uid = 0
```
to the kubernetes config file

**Closed by yakutovicha** 2019-12-03 17:26 UTC

**Comment by yakutovicha** [comment] 2020-01-31 17:42
To keep in mind, that there is another `init`: https://github.com/krallin/tini
